---
title: "Injuries in the NFL"
author: "Christopher Spartz"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r setup-libs}
library(rvest)
library(stringr)
library(tidyverse)
library(ggplot2)
library(purrr)
#library(lubridate)
library(xml2)

teamids <- c('mia','nwe','buf','nyj','pit','rav','cin','cle','jax','oti',
           'htx','clt','kan','sdg','rai','den','phi','dal','was','nyg',
           'min','det','gnb','chi','nor','car','atl','tam','ram','sea',
           'crd','sfo')
years <- c(2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020)
```

```{r inj-func}
team_inj <- function(t) {
  c <- 1
  tinj <- list()
  for (y in seq_along(years)) {
    url <- sprintf("https://www.pro-football-reference.com/teams/%s/%d_injuries.htm",t,years[y])
    i <- url %>%
      read_html()%>%
      html_node('table#team_injuries')%>%
      html_table()
    i <- i[c(1:17)]
    names(i) <- c("Player","Game_1","Game_2","Game_3","Game_4","Game_5","Game_6","Game_7","Game_8","Game_9",
              "Game_10","Game_11","Game_12","Game_13","Game_14","Game_15","Game_16")
    i <- i %>% pivot_longer(!c("Player"),names_to = "Game",values_to = "Injury")
    i <- i %>% separate(Game,c(NA,"Game"),"_")
    i <- i[!(is.na(i$Injury) | i$Injury==""), ]
    i <- i %>% mutate(year=years[y],
                  team=t)
    i$Player <- as.factor(i$Player)
    tinj[[c]] <- i
    c <-  c+1
  }
  big_inj <- tinj %>% bind_rows()
}
```
```{r all-inj}
teaminj <- list()
c <- 1
for (t in seq_along(teamids)) {
  teaminj[[c]] <- team_inj(teamids[[t]])
  c <- c+1
}
all_inj <- teaminj %>% bind_rows()
```

```{r}
all_inj <- all_inj %>% filter(Injury!="//")
all_inj <- all_inj %>% filter(Injury!="//;90")
all_inj$Injury <- as.factor(all_inj$Injury)
all_inj %>% group_by(Injury) %>% count(Injury)
```


```{r starter-func}
team_starters <- function(t) {
  url <- sprintf("https://www.pro-football-reference.com/teams/%s/lineups.htm#starting_lineups",t)
  lin <- read_html(url)
  p <- lin %>%
    html_node('table#starting_lineups')
  
  xml_find_all(p, ".//br") %>% xml_add_sibling("p", "\n")

  xml_find_all(p, ".//br") %>% xml_remove()
  p <- p %>% html_table()
  p <- p %>% pivot_longer(!c("Year","Record"),names_to = "Position Group",values_to = "Players") %>% filter(Year>2009)
  p1 <- p %>% separate(Players,c("Player_1","Player_2","Player_3","Player_4","Player_5","Player_6"),sep = "\n")
  p2 <- p1 %>% pivot_longer(!c("Year","Record","Position Group"),names_to = "Field") %>% na.omit()
  p3 <- p2 %>% mutate(value = str_replace(value, "\\s", "|")) %>% 
    separate(value, into = c("Position", "Player"), sep = "\\|")
  p3$"Player" <- str_remove_all(p3$'Player','[*+]')
  p3 <- p3 %>% select(-Field)
  p3 <- p3 %>% mutate(team=t)
}
```

```{r}
teamStart <- list()
c <- 1
for (t in seq_along(teamids)) {
  teamStart[[c]] <- team_starters(teamids[[t]])
  c <- c+1
}
all_starters <- teamStart %>% bind_rows()
all_starters$Player <- as.factor(all_starters$Player)
```


```{r join-dbs}
all_starters$Player <- str_trim(all_starters$Player)
alltogether <- all_starters %>% rename(year=Year) %>% inner_join(all_inj, by=c("Player","year","team"))
```


```{r inj-by-year}
all_inj %>% group_by(Injury,year) %>% count(Injury) %>% unique() %>%
  ggplot(aes(x=Injury,y=n, fill=Injury)) +
  geom_bar(stat = "Identity") + 
  facet_wrap(~year)
```

```{r}
alltogether %>% group_by(Position) %>% count(Position)
```



```{r inj-by-position}
alltogether %>% group_by(Injury,Position) %>% count(Injury) %>%
  ggplot(aes(x=Injury,y=n, fill=Injury)) +
  geom_bar(stat = "Identity") + 
  facet_wrap(~Position)
```










